### ISSUE TITLE
support for dependency:/ syntax

### ISSUE THREAD

**Issue by gmaricha** [cmarchand/gaulois-compiler-maven-plugin#3]
Christophe,

The plugin should be updated in order to support the  dependency:/ protocol syntax.

TIA,
        Gilles

**Comment by cmarchand** [comment]
@gmaricha : on which project did you have the problem. I need something to debug in...

**Comment by gmaricha** [comment]
@cmarchand : on sie-flash-prio-import-dep-els-jurisprudence
A+,

**Comment by cmarchand** [comment]
Only the xsl that compiles the gaulois-compile file has to be corrected.
Probably, I should send the mapping (xslUri, sefUri) to XSL as parameter...
Or do a resolver-uri in XSL, but this mean code is duplicated...

**Comment by cmarchand** [comment]
Release [1.1.2](http://repo1.maven.org/maven2/top/marchand/xml/maven/gaulois-compiler-maven-plugin/1.1.2/) has been published.
