### ISSUE TITLE
Sometimes there is a child node under <file> but it is not another file

### ISSUE THREAD

**Issue by AxelCourt** [cmarchand/gaulois-compiler-maven-plugin#5]
(Pouêt pouêt Christophe ! J'espère que tu vas bien ! :))

Hi there!

I found an issue in the schema/sub-schemas processing algorithm.
Sometimes the "XUT" XSL adds `<report>` elements under `<file>` to add information about the parent file (e.g. that the file is duplicated).
For instance:

```
<schemas>
   <file dependency-type="xsl:import-schema"
         name="schema.xsd"
         uri="grammar/schema.xsd"
         abs-uri="jar:file:path/to/file/grammar/schema.xsd"/>
   <file dependency-type="xsl:import-schema"
         name="schema.xsd"
         uri="grammar/schema.xsd"
         abs-uri="jar:file:path/to/file/grammar/schema.xsd">
      <report role="info" code="duplicatedDependency">This file has already been processed</report>
   </file>
</schemas>
```

In that case we get a _NullPointerException_ because only a `<file>` child element is expected and some variables are left with null values.

I am going to submit a pull request for this!

Cheers,
Axel

**Comment by AxelCourt** [comment]
See PR #6.

**Comment by cmarchand** [comment]
Thanks !
So you now package compiled XSL ? ! Nice !

**Comment by cmarchand** [comment]
Release 1.1.5 created, published on maven central.
I've also bumped xerces 2.12.0, due to vulnerabilities with 2.11.0.
See you...
